---
- name: "get docker info"
  shell: docker info
  register: docker_info
  changed_when: false

- name: "join as a worker"
  shell: "docker swarm join --token {{ hostvars['swarm-01']['worker_token']['stdout'] }} {{ hostvars['swarm-01']['ansible_eth0']['ipv4']['address'] }}:2377"
  when: docker_info.stdout.find("Swarm{{':'}} inactive") != -1
  retries: 3
  delay: 20
