version: "3"

services:
  jenkins:
    image: jenkins
    ports:
      - '8082:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/var/jenkins_home'

volumes:
  jenkins_data:
    driver: local
