version: "3"

services:
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul

  registrator:
    image: gliderlabs/registrator:latest
    command: "consul://consul:8500"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    networks:
      - consul

networks:
  consul:
