version: "3"
services:
  monitoring:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
